spring:
  datasource:
    url: jdbc:mysql://localhost:3306/platform?autoReconnect=true&characterEncoding=utf-8&zeroDateTimeBehavior=CONVERT_TO_NULL&serverTimezone=GMT&useSSL=false
    name: platform
    username: root
    password: root
#    type: com.alibaba.druid.pool.DruidDataSource
#    druid:
#      master:
#        url: jdbc:mysql://localhost:3306/platform?autoReconnect=true&characterEncoding=utf-8&zeroDateTimeBehavior=CONVERT_TO_NULL&serverTimezone=GMT&useSSL=false
#        name: bill
#        username: root
#        password: root